lint: {}
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: author_field
  description: DualRNA-seq pipeline for the analysis of bacterial and host transcriptomes
  force: false
  is_nfcore: true
  name: dualrnaseq
  org: nf-core
  outdir: .
  version: 1.0.0
